import '@/styles/index.scss';
import type { Metadata } from 'next';
import { Titillium_Web } from 'next/font/google';

import Providers from '@/providers/Providers';

const titillium = Titillium_Web({ subsets: ['latin'], weight: ['400', '600', '900'] });

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-theme="dark" className={titillium.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
